'use client';
import { Inter, Pacifico } from 'next/font/google';

import { Provider } from '@/components';

import '../styles/global.css';

export const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const pacifico = Pacifico({
  weight: ['400'],
  variable: '--font-pacifico',
  subsets: ['latin', 'cyrillic'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${pacifico.variable} ${inter.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
